# Lesson 8 homework

In [3]:
import numpy as np

#task1
array1 = np.zeros(10)
array1[5] = 1
print(array1)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [5]:
#task2
array2 = np.arange(10,50)
print(array2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [6]:
#task3
array3 = array2[::-1]
print(array3)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [7]:
#task4
matrix1 = np.arange(9).reshape(3,3)
print(matrix1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#task5
array4 = np.array([1,2,0,0,4,0])
non_zero = np.nonzero(array4)[0]
print(non_zero)

[0 1 4]


In [ ]:
#task6
indentity_matrix = np.eye(3)
print(indentity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
#task7
random_matrix = np.random.rand(3, 3)
min_val = np.min(random_matrix)
max_val = np.max(random_matrix)
print(random_matrix)
print("Minimum value:", min_val)
print("Maximum value:", max_val)

[[0.45840589 0.74277066 0.55744375]
 [0.78820199 0.40371698 0.77729412]
 [0.42578236 0.90029194 0.55159002]]
Minimum value: 0.4037169786017022
Maximum value: 0.9002919427920228


In [ ]:
#task8
random_matrix_5 = np.random.rand(5,5)
normalized_matrix = (random_matrix_5 - np.min(random_matrix_5))/(np.min(random_matrix_5))
print('Normalized matrix: ', normalized_matrix)

Normalized matrix:  [[ 5.00934366  1.56620856  4.33901176  8.63036677  8.72695334]
 [ 7.63009188  2.59347539  9.23547049 11.06263198  4.00856382]
 [ 2.71777866  9.88593229  7.63441509  3.773553    0.        ]
 [ 2.81132338  6.54289055  7.42402889 11.09730801 12.22973014]
 [ 7.30549491  3.59875787  3.73329281 11.77088122 10.14179455]]


In [13]:
#task9
array5 = np.array([1,3,5,11,15,20,25])
target = 14
closest = array5[(np.abs(array5 - target)).argmin()]
print(closest)

15


In [15]:
#task10
array6 = np.array([[5,9,3],[10,2,15],[6,7,8]])
for row in range(array6.shape[0]):
    row_matrix_index = array6[row].argmax()
    array6[row, row_matrix_index] = 0
print(array6)

[[ 5  0  3]
 [10  2  0]
 [ 6  7  0]]


In [17]:
#task11
array7 = np.array([2, 3, 2, 5, 8, 3, 3, 7, 2, 3, 5, 5, 5, 5])
common_value = np.bincount(array7).argmax()
print(common_value)


5


In [18]:
#task12
array8 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_product = np.dot(array8, array8.T)
print(matrix_product)

[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


In [19]:
#task13
matrix2 = np.array([[6, 1, 1], [4, -2, 5], [2, 8, 7]])
determinant = np.linalg.det(matrix2)
print(determinant)

-306.0


In [20]:
#task14
matrix3 = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
try:
    inverse_matrix = np.linalg.inv(matrix3)
    print("\nInverse of the matrix:\n", inverse_matrix)
except np.linalg.LinAlgError:
    print("\nMatrix is singular (non-invertible) and does not have an inverse.")


Inverse of the matrix:
 [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
